package Paneles;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelos.m_clases;

/**
 *
 * @author Jaime Bueno Perez
 */
public class panel_mostrar_clases extends javax.swing.JPanel {

    private Interfaz.principal panelPrincipal;

    public panel_mostrar_clases(Interfaz.principal panelPrincipal, String panelretorno) throws IOException {
        this.panelPrincipal = panelPrincipal;
        initComponents();

        m_clases clase = new m_clases();
        List<m_clases> clases = clase.getAll();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Horarios");
        model.addColumn("Descripcion");
        model.addColumn("Delete_Status");
        
        table.setModel(model);

        for (m_clases cl : clases) {
            String nombre = cl.getNombre();
            Object[] rowData = {
                cl.getId(),
                cl.getNombre(),
                cl.getHorarios(),
                cl.getDescripcion(),
                cl.getDelete_status()
            };
            model.addRow(rowData);
        }

        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int filaSeleccionada = table.getSelectedRow();
                if (filaSeleccionada != -1) {
                    int id = (int) table.getValueAt(filaSeleccionada, 0);
                    String nombre = (String) table.getValueAt(filaSeleccionada, 1);
                    String horarios = (String) table.getValueAt(filaSeleccionada, 2);
                    String descripcion = (String) table.getValueAt(filaSeleccionada, 3);
                    int delete_status = (int) table.getValueAt(filaSeleccionada, 4);

                    clase.setId(id);
                    clase.setNombre(nombre);
                    clase.setHorarios(horarios);
                    clase.setDescripcion(descripcion);
                    clase.setDelete_status(delete_status);

                    try {
                        if (panelretorno == "panel_gestionar_clase") {
                            new Paneles.CambiaPanel(panelPrincipal.getPanel_central(), new panel_gestionar_clase(panelPrincipal, clase));
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(panel_mostrar_clases.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    panelPrincipal.revalidate();
                    panelPrincipal.repaint();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 660));
        setLayout(new java.awt.GridBagLayout());

        jScrollPane.setBorder(null);
        jScrollPane.setAutoscrolls(true);
        jScrollPane.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Ciudad", "Localidad", "Codigo Postal", "Telefono", "Horario", "Delete Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setMinimumSize(new java.awt.Dimension(225, 68));
        table.setName(""); // NOI18N
        table.setRowHeight(17);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
